name: botica_san_antonio
description: Sistema móvil para Botica San Antonio
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  mobile_scanner: ^3.5.6
  fl_chart: ^0.67.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  http: ^1.2.0
  pdf: ^3.10.7
  printing: ^5.12.0
  excel: ^2.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/